[project]
name = "assignment5-mlops"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasets>=4.2.0",
    "huggingface-hub>=0.35.3",
    "torchvision>=0.23.0",
    "transformers>=4.57.0",
    "wandb>=0.22.2",
]
